{% set name = "vala" %}
{% set version = "0.56.15" %}
{% set minor_version = '.'.join(version.split('.')[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.gnome.org/sources/vala/{{ minor_version }}/vala-{{ version }}.tar.xz
  sha256: 535b6452ed310fd5fb5c7dd6794b6213dac3b48e645e5bff3173741ec2cb3f2b

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - bison
    - flex
    - make
  host:
    - glib
    - gobject-introspection

test:
  files:
    - test.vala
  commands:
    - valac test.vala && ./test

about:
  home: https://gitlab.gnome.org/GNOME/vala
  summary: Compiler for the GObject type system
  license: LGPL-2.1-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - xhochy
