{% set name = "vala" %}
{% set version = "0.56.17" %}
{% set minor_version = '.'.join(version.split('.')[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.gnome.org/sources/vala/{{ minor_version }}/vala-{{ version }}.tar.xz
  sha256: 26100c4e4ef0049c619275f140d97cf565883d00c7543c82bcce5a426934ed6a

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - pkg-config
    - bison
    - flex
    - make
  host:
    - glib
    - gobject-introspection

test:
  files:
    - test.vala
  commands:
    - valac test.vala && ./test

about:
  home: https://gitlab.gnome.org/GNOME/vala
  summary: Compiler for the GObject type system
  license: LGPL-2.1-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - xhochy
